apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seleniumgrid
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: seleniumgrid
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: selenium-grid
    repoURL: https://thomas-personal.github.io/seleniumhelm/
    targetRevision: 0.26.6
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true